#!/usr/bin/env node
const fs=require('fs'); const PptxGenJS=require('pptxgenjs');
const C={navy:'002869',cobalt:'0057AF',opal:'1F96FF',crystal:'E0F1FF',onyx:'00002D',gray:'707996',white:'FFFFFF'}; const F='Arial';
function meta(s){let m={},a=s.trim().split(/\n/);while(a.length&&/^[\w-]+:/.test(a[0])){let x=a.shift().match(/^([\w-]+):\s*(.*)$/);m[x[1]]=x[2]}return [m,a.join('\n').trim()]}
function parse(md){let a=md.trim().split(/^---\s*$/m).map(x=>x.trim()).filter(Boolean),d={};if(a[0]&&!a[0].includes('\ntype:'))[d]=meta(a.shift());return[d,a.map(x=>{let[m,b]=meta(x);m.body=b;return m})]}
function footer(slide,c,n){slide.addShape('rect',{x:.55,y:7.14,w:12.2,h:.012,fill:{color:C.gray},line:{transparency:100}});slide.addText(c||'RESTRICTED',{x:.58,y:7.18,w:2,h:.15,fontFace:F,fontSize:7,color:C.gray,margin:0});slide.addText(String(n),{x:12.35,y:7.16,w:.4,h:.16,fontFace:F,fontSize:8,color:C.gray,align:'right',margin:0})}
function base(p,title,c,n,bg=C.white){let s=p.addSlide();s.background={color:bg};s.addText(title||'',{x:.72,y:.45,w:11.85,h:.72,fontFace:F,fontSize:28,bold:true,color:C.onyx,margin:0,fit:'shrink'});s.addShape('rect',{x:.72,y:1.3,w:1,h:.035,fill:{color:C.cobalt},line:{transparency:100}});footer(s,c,n);return s}
function bullets(b){return b.split(/\n/).filter(x=>/^\s*[-*]\s+/.test(x)).map(x=>x.replace(/^\s*[-*]\s+/,''))}
async function build(i,o){let[d,ss]=parse(fs.readFileSync(i,'utf8')),p=new PptxGenJS();p.layout='LAYOUT_WIDE';p.author=d.presenter||'';p.title=d.title||'';ss.forEach((x,k)=>{let n=k+1,s,t=x.type||'bullets';if(t==='title'){s=p.addSlide();s.background={color:C.navy};s.addText(x.title||d.title||'',{x:1,y:1.3,w:11.2,h:2,fontFace:F,fontSize:35,bold:true,color:C.white,margin:0,fit:'shrink'});s.addText(x.subtitle||d.subtitle||'',{x:1,y:4,w:10,h:.7,fontFace:F,fontSize:18,color:'B8DEFF',margin:0,fit:'shrink'});footer(s,x.classification||d.classification,n)}else if(t==='takeaway'){s=base(p,x.title,x.classification||d.classification,n,C.crystal);s.addShape('roundRect',{x:1.15,y:1.75,w:11,h:3.8,fill:{color:C.navy},line:{color:C.navy}});s.addText(x.body,{x:1.7,y:2.3,w:9.9,h:2.3,fontFace:F,fontSize:28,bold:true,color:C.white,align:'center',valign:'mid',fit:'shrink'})}else if(t==='two-column'){s=base(p,x.title,x.classification||d.classification,n);let cs=x.body.split(/^::: column\s*$/m).map(z=>z.trim()).filter(Boolean).slice(0,2);cs.forEach((z,j)=>{let ls=z.split(/\n/),h=(ls.shift()||'').replace(/^#+\s*/,''),it=bullets(ls.join('\n'));s.addShape('roundRect',{x:.72+j*6.11,y:1.58,w:5.78,h:4.95,fill:{color:j?C.crystal:'F4F8FC'},line:{color:'B8DEFF'}});s.addText(h,{x:1+j*6.11,y:1.88,w:5.2,h:.5,fontFace:F,fontSize:21,bold:true,color:C.cobalt,fit:'shrink'});s.addText(it.map((q,z)=>({text:q,options:{bullet:{indent:18},breakLine:z<it.length-1}})),{x:1+j*6.11,y:2.55,w:5.05,h:3.5,fontFace:F,fontSize:17,color:C.onyx,fit:'shrink'})})}else{s=base(p,x.title,x.classification||d.classification,n);let it=bullets(x.body);s.addText(it.length?it.map((q,z)=>({text:q,options:{bullet:{indent:18},breakLine:z<it.length-1}})):x.body,{x:.88,y:1.65,w:11.3,h:4.9,fontFace:F,fontSize:20,color:C.onyx,margin:.05,fit:'shrink',breakLine:false})}});await p.writeFile({fileName:o})}
let i=process.argv[2],o=process.argv[3]||'output.pptx';if(!i){console.error('Usage: node md2ppt.js input.md output.pptx');process.exit(2)}build(i,o).catch(e=>{console.error(e);process.exit(1)});
